[config]
schemaVersion = "0.0.1"

[package]
namespace = "LanChelms"
name = "DeepNorthModpack"
versionNumber = "0.2.0"
description = "A pack of mods for the LanChelms Deep North Valheim server."
websiteUrl = "https://github.com/jterrace/lanchelms-valheim-mods"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "config"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]
[publish.categories]
valheim = [ "modpacks", "server-side", "client-side" ]

[package.dependencies]
"Advize-StumpsRegrow" = "1.0.5"
"Azumatt-MaxPlayerCount" = "1.2.4"
"RustyMods-Seasonality" = "3.8.0"
"ValheimModding-YamlDotNet" = "16.3.1"
"denikson-BepInExPack_Valheim" = "5.4.2333"
