[config]
schemaVersion = "0.0.1"

[package]
namespace = "LanChelms"
name = "DeepNorthModpack"
versionNumber = "1.5.0"
description = "A pack of mods for the LanChelms Deep North Valheim server."
websiteUrl = "https://github.com/jterrace/lanchelms-valheim-mods"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "config"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]
[publish.categories]
valheim = [ "modpacks", "server-side", "client-side" ]

[package.dependencies]
"Advize-PlantEasily" = "2.1.1"
"Advize-PlantEverything" = "1.20.0"
"Advize-StumpsRegrow" = "1.0.5"
"Azumatt-AAA_Crafting" = "2.1.6"
"Azumatt-AzuAntiCheat" = "4.3.11"
"Azumatt-AzuCraftyBoxes" = "1.8.14"
"Azumatt-AzuExtendedPlayerInventory" = "2.4.1"
"Azumatt-AzuWearNTearPatches" = "1.0.8"
"Azumatt-Foglands" = "1.0.1"
"Azumatt-MaxPlayerCount" = "1.2.4"
"Azumatt-Where_You_At" = "1.0.11"
"ComfyMods-Gizmo" = "1.15.0"
"Digitalroot-Better_Wisps" = "1.0.42"
"DrummerCraig-OneMapToRuleThemAll" = "1.2.2"
"JereKuusela-Server_devcommands" = "1.106.0"
"MSchmoecker-TimeoutLimit" = "0.2.0"
"Meldurson-AllTameableTamingOverhaul" = "1.5.4"
"MidnightMods-Mistward" = "0.7.3"
"MidnightMods-ValheimInfiniteFire" = "1.1.0"
"Nextek-SpeedyPaths" = "1.0.9"
"Radamanto-BiomeLock" = "1.1.4"
"RustyMods-Seasonality" = "3.8.0"
"Searica-SkilledCarryWeight" = "1.4.1"
"Smoothbrain-ServerCharacters" = "1.4.16"
"Smoothbrain-TargetPortal" = "1.2.3"
"ValheimModding-Jotunn" = "2.29.0"
"ValheimModding-JsonDotNET" = "13.0.4"
"ValheimModding-YamlDotNet" = "16.3.1"
"Vapok-BetterSleepBruh" = "1.0.2"
"VentureValheim-Mining_Caves" = "0.3.1"
"VentureValheim-Venture_Location_Reset" = "0.10.8"
"VentureValheim-World_Advancement_Progression" = "0.3.14"
"VitByr-VBNetTweaks" = "0.3.0"
"denikson-BepInExPack_Valheim" = "5.4.2333"
"malafein-ShipwrightsTouch" = "1.0.2"
"nwesterhausen-DiscordConnector" = "3.1.2"
"shudnal-ItemStacksItemWeights" = "1.0.7"
"shudnal-LongshipUpgrades" = "1.0.16"
"shudnal-TradersExtended" = "1.3.13"
